### ISSUE TITLE
You must recompile your plugin for x64 arquitecture?

### ISSUE THREAD

**Issue by ArsLucidum** [doitian/nfd-unity3d#1]
Hi, I'm having trouble with the wrapper. Unity gives me the following error:

```
Failed to load 'Assets/nfd/Plugins/x86_64/nfd.dll', expected x64 architecture, but was x86 architecture. You must recompile your plugin for x64 architecture.
nfd.NativeFileDialog:OpenDialog(String, String, String&) (at Assets/nfd/Scripts/nfd/NativeFileDialog.cs:42)
nfd.NativeFileDialog:OpenDialog(String, String, String&) (at Assets/nfd/Scripts/nfd/NativeFileDialog.cs:28)
nfd.FileDialog:Show() (at Assets/nfd/Scripts/nfd/FileDialog.cs:37)
UnityEngine.EventSystems.EventSystem:Update()
```

I don't know why the problem arises, since it appears to be using the correct path for the x64 version. Any idea?

If the library happens to be wrong, is there any way where I can download it in binary form?

**Comment by doitian** [comment]
I miss the arch in build script. The DLL has been recompiled.

**Comment by ArsLucidum** [comment]
@doitian Thanks for the quick reply! It works perfectly now.
